apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-demo-0-pv
  labels:
    type: MyApp
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
