apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-web-disk-pv-volume-0
  labels:
    type: MyApp
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
